### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'Pipfile'

### ISSUE THREAD

**Issue by CoreyCole** [VaultVulp/pipenv-alpine#1]
My dockerfile:
```
FROM vaultvulp/pipenv-alpine

ENV PYTHONPATH /Halloo/src/
ENV MYPYPATH /Halloo/src/backend/stubs

WORKDIR /Halloo/src/backend
RUN pipenv install

WORKDIR /Halloo/
```
I'm getting error:
```
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 366, in install
    selective_upgrade=selective_upgrade,
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1730, in do_install
    skip_requirements=skip_requirements,
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 600, in ensure_project
    project.touch_pipfile()
  File "/usr/local/lib/python3.6/site-packages/pipenv/project.py", line 541, in touch_pipfile
    with open('Pipfile', 'a'):
PermissionError: [Errno 13] Permission denied: 'Pipfile'
```

**Comment by CoreyCole** [comment]
It was a misleading error - it wasn't permissions. It was simply because I didn't `COPY` in my Pipfile and Pipfile.lock
